repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

missingFileHandler: Error

releases:
  - name: "cert-manager-clusterissuer"
    namespace: "cert-manager"
    labels:
      chart: "raw"
      repo: "incubator"
      namespace: "cert-manager"
      vendor: "helm"
    chart: "incubator/raw"
    version: "0.2.3"
    wait: true
    atomic: true
    cleanupOnFail: true
    values:
      - resources:
          - apiVersion: cert-manager.io/v1alpha2
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-staging
            spec:
              acme:
                # The ACME server URL
                server: https://acme-staging-v02.api.letsencrypt.org/directory
                # Email address used for ACME registration
                email: {{ requiredEnv "LETSENCRYPT_EMAIL" | quote }}
                # Name of a secret used to store the ACME account private key
                privateKeySecretRef:
                  name: letsencrypt-staging
                # Enable the HTTP-01 challenge provider
                solvers:
                  - http01:
                      ingress: {}
          - apiVersion: cert-manager.io/v1alpha2
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-production
            spec:
              acme:
                # The ACME server URL
                server: https://acme-v02.api.letsencrypt.org/directory
                # Email address used for ACME registration
                email: {{ requiredEnv "LETSENCRYPT_EMAIL" | quote }}
                # Name of a secret used to store the ACME account private key
                privateKeySecretRef:
                  name: letsencrypt-production
                # Enable the HTTP-01 challenge provider
                solvers:
                  - http01:
                      ingress: {}
